config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :messages do
        resources :comments
    end


    root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_message
  before_action :find_comment , only: [ :edit, :update , :destroy]
  before_action :authenticate_user!

  def create
    #@message = Message.find(params[:message_id])
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id


    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end

  end

  def edit
    #@message = Message.find(params[:message_id])
    #@comment = @message.comments.find(params[:id])
  end

  def update
    if @comment.update(comment_params)
        redirect_to message_path(@message)
    else
       render 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
    
    def find_message
        @message = Message.find(params[:message_id])
    end

    def find_comment
       @comment = @message.comments.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

before_action :find_message , only: [:show ,:edit ,:update ,:destroy]
before_action :authenticate_user!, except: [ :index , :show]
  

  def index
    @message = Message.all.order("created_at DESC").paginate(page: params[:page], per_page: 3)
    #@message = Message.all.order("created_at DESC")
  end

  def new
    #@message = Message.new    #[one to many association]
    @message = current_user.messages.build
  end

  def show
  end

  def create
    #@message = Message.new(message_params)
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path
    else
      render 'new'
    end

  end


  def edit
  end

  def update #just like create 
    if @message.update(message_params)
      redirect_to message_path #show
    else
       render 'edit'
    end    
  end

  def destroy
     @message.destroy
     redirect_to root_path
    
  end

  private

  def message_params
    params.require(:message).permit(:title , :description)
  end 

  def find_message
    @message=Message.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<hr>
<p> <%= comment.content %> </p>
<p><b>Posted by</b> <u><%= comment.user.email %> <%= time_ago_in_words(comment.created_at)%> </u>
ago
</p>
<% if user_signed_in? %>
   <% if comment.user_id == current_user.id %> 
      <%= link_to "Edit" , edit_message_comment_path(comment.message, comment) %>
      <%= link_to "Delete" , message_comment_path(comment.message, comment), method: :delete, data:{confirm: "Are you sure ?"} %>
   <% end%>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build])  do |f|%>
    <%= f.input :content, label: "Comment"%>
    
    <%= f.button :submit %>

<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message , @comment])  do |f|  %>
  <%= f.input :content , label: "Comment"%>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <div class="navbar navbar-default ">
            <div class="container">
            <div class="navbar-header">
                <%= link_to "Message_boad" , root_path , class: "navbar-brand"%>
            </div>
            <ul class="nav navbar-nav">
                <li><%= link_to "Sign_Up" , new_user_registration_path %></li>
                <% if user_signed_in? %>
                      <li><%= link_to "Sign_Out" , destroy_user_session_path , method: :delete %> </li>
                      <%  else %>
                      <li> <%= link_to "Log_in" , new_user_session_path%></li>
                      <%  end %>
            </ul>
            <% if user_signed_in?%>
              <p>
                <%= link_to "New Message" , new_message_path , class: "navbar-right navbar-text navbar-link"%>

              </p>
            <% end %>
            </div>

        </div>


        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <div class= "container">
            <%= yield %>
        </div>    
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title , label: "Message Title" %>
  <%= f.input :description ,  label: "Message Description"%>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1> Edit Form</h1>

<%= render 'form'  %>

app/views/messages/index.html.erb
 

<%  @message.each do |mess|   %>

<div class="col-md-4">
  <div class="message">
      <h2 class= "message-title">  <%= mess.title %> </h2>
      <%= link_to "view Message" , message_path(mess) , class:"btn-custom" %>
  </div>
</div>
<%  end %>
<br>
<hr>
<%= will_paginate @message,   renderer: BootstrapPagination::Rails   ,previous_label: "Older", next_label: "Newer", inner_window: 1, outer_window:0 %>

<!-- 

<%= will_paginate @message %>
 -->

app/views/messages/new.html.erb
<h1> New Message</h1>

<%= render 'form'  %>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">

  <div class="message-show">
      <h1><%= @message.title %></h1>
      <p class="message-posted-by"><u>Posted</u> by <sup><%= @message.user.email %></sup> <sub> <b><%= time_ago_in_words(@message.created_at)%> </b></sub>
      ...ago
      </p>
      <br/>
      <p class="message-desc"><%= @message.description %></p>
          <br>
            <hr>

                <h3>Comments: </h3>
                <%= render @message.comments %>
                
                <h3 class="reply-to-msg ">Reply to Message: </h3>
                <%= render 'comments/form' %>
            <hr>
         <div class="links btn-group">             
                <%= link_to "Back",  messages_path, class: "btn btn-default"%>

                  <% if user_signed_in? %>
                      <% if @message.user_id == current_user.id %>
                          
                          <%= link_to "Edit Message" , edit_message_path(@message) , class: "btn btn-default"%>
                          <%= link_to "Delete",  message_path(@message) , method: :delete, data: { confirm: "Are you Sure ?"} , class: "btn btn-default"%>
                      <% end%>
                   <% end%>
                </div>
                </div>
          </div>